require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/passengers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Passenger. As you add validations to Passenger, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Passenger.create! valid_attributes
      get passengers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      passenger = Passenger.create! valid_attributes
      get passenger_url(passenger)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_passenger_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      passenger = Passenger.create! valid_attributes
      get edit_passenger_url(passenger)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Passenger" do
        expect {
          post passengers_url, params: { passenger: valid_attributes }
        }.to change(Passenger, :count).by(1)
      end

      it "redirects to the created passenger" do
        post passengers_url, params: { passenger: valid_attributes }
        expect(response).to redirect_to(passenger_url(Passenger.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Passenger" do
        expect {
          post passengers_url, params: { passenger: invalid_attributes }
        }.to change(Passenger, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post passengers_url, params: { passenger: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested passenger" do
        passenger = Passenger.create! valid_attributes
        patch passenger_url(passenger), params: { passenger: new_attributes }
        passenger.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the passenger" do
        passenger = Passenger.create! valid_attributes
        patch passenger_url(passenger), params: { passenger: new_attributes }
        passenger.reload
        expect(response).to redirect_to(passenger_url(passenger))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        passenger = Passenger.create! valid_attributes
        patch passenger_url(passenger), params: { passenger: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested passenger" do
      passenger = Passenger.create! valid_attributes
      expect {
        delete passenger_url(passenger)
      }.to change(Passenger, :count).by(-1)
    end

    it "redirects to the passengers list" do
      passenger = Passenger.create! valid_attributes
      delete passenger_url(passenger)
      expect(response).to redirect_to(passengers_url)
    end
  end
end
